# -*- coding: utf-8 -*-
"""advertising .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCico5v18SakPHZiYcz3yWm27ZbWvvvN

This data set contain the following features:


*   **Daily Time Spend On Site**:consumer time on site in minutes
*   **Age**:customer age in year
*   **Area Incom**:Avg incom geograghical area of consumer
*   **Ad Topic Line**:Headline of the advertisment
*   **City**:city of consumer
*   **Male**:if male is 1 or not is 0
*  **Country**:country of consumer
*   **Timestamp**:Time at witch consumer clicked on Ad or closed on window
*   **Click on Ad**:0 or 1 indicated clicking on Ad
"""

import numpy as np 
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.

import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import files
uploaded=files.upload()

import io
ad_train=pd.read_csv(io.BytesIO(uploaded['advertising.csv']))

ad_train.head()

ad_train.describe()

ad_train.info()

ad_train['Age'].plot.hist(bins=30)

sns.displot(ad_train['Age'].dropna(),kde=False,bins=30)

sns.jointplot(x="Age",y='Area Income',data=ad_train)

sns.jointplot(x="Age",y='Daily Time Spent on Site',data=ad_train,kind="kde",color="red")

sns.pairplot(ad_train,hue="Clicked on Ad")

ad_train.head(1)

X=ad_train[["Daily Time Spent on Site",'Age','Area Income','Daily Internet Usage','Male']]
y=ad_train['Clicked on Ad']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.linear_model import LogisticRegression

logmodel=LogisticRegression()
logmodel.fit(X_train,y_train)

predictions=logmodel.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,predictions))

print(confusion_matrix(y_test,predictions))